ProjetAsp/ProjetAsp/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjetAsp.Models;

namespace ProjetAsp.Controllers
{
    [Authorize(Roles = "admin")]
    public class CategoriesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Categories
        public ActionResult Index()
        {
            return View(db.CategoriesSet.ToList());
        }

        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.CategoriesSet.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoryID,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.CategoriesSet.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.CategoriesSet.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategoryID,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.CategoriesSet.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.CategoriesSet.Find(id);
            db.CategoriesSet.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjetAsp/ProjetAsp/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjetAsp.Models;
using Microsoft.AspNet.Identity;
using System.Globalization;
using System.Threading;

namespace ProjetAsp.Controllers
{
    
    public class ItemsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Items
        [Authorize]
        public ActionResult Index()
        {
            var itemsSet = db.itemsSet.Where(x=>x.Available == true).Include(i => i.Category).Include(i => i.User);
            
            return View(itemsSet.ToList());
        }

        public ActionResult CultureFR(string returnUrl)
        {
            Session["Culture"] = new CultureInfo("fr");
            Thread.CurrentThread.CurrentUICulture = (CultureInfo)Session["Culture"];
            Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(((CultureInfo)Session["Culture"]).Name);

            return RedirectToLocal(returnUrl);
        }

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult CultureEn(string returnUrl)
        {
            Session["Culture"] = new CultureInfo("en");
            Thread.CurrentThread.CurrentUICulture = (CultureInfo)Session["Culture"];
            Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(((CultureInfo)Session["Culture"]).Name);

            return RedirectToLocal(returnUrl);
        }

        [Authorize]
        // GET: Items/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.itemsSet.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }
        [Authorize]
        public ActionResult Emprunter(int? id)
        {

            if (!id.HasValue)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           Item a = db.itemsSet.Find(id);
            if(a == null)
            {
                return HttpNotFound();
            }

            Trade unTrade = new Trade();
            a.Available = false;
            unTrade.Item = a;
            unTrade.StartDate = DateTime.Now;
            unTrade.UserID = User.Identity.GetUserId();

            unTrade.EndDate = unTrade.StartDate.AddDays(a.tempsMax);
            db.TradesSet.Add(unTrade);
            db.Entry(a).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        [Authorize]
        // GET: Items/Create
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.CategoriesSet, "CategoryID", "Name");
           
            return View();
        }

        // POST: Items/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "ItemID,ItemName,CategoryID,tempsMax")] Item item)
        {
            
            if (ModelState.IsValid)
            {
                item.UserID = User.Identity.GetUserId();
                item.Available = true;
                item.Trades = new List<Trade>();
                db.itemsSet.Add(item);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.CategoriesSet, "CategoryID", "Name", item.CategoryID);
            //ViewBag.UserID = new SelectList(db.Users, "Id", "Email", item.UserID);
            return View(item);
        }

        // GET: Items/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.itemsSet.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.CategoriesSet, "CategoryID", "Name", item.CategoryID);
            //ViewBag.UserID = new SelectList(db.Users, "Id", "Email", item.UserID);
            return View(item);
        }

        // POST: Items/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Edit([Bind(Include = "ItemID,ItemName,CategoryID,Available,UserID")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.CategoriesSet, "CategoryID", "Name", item.CategoryID);
            //ViewBag.UserID = new SelectList(db.Users, "Id", "Email", item.UserID);
            return View(item);
        }

        // GET: Items/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.itemsSet.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Item item = db.itemsSet.Find(id);
            db.itemsSet.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjetAsp/ProjetAsp/Controllers/StatistiqueController.cs
using ProjetAsp.Models;
using ProjetAsp.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjetAsp.Controllers
{
    public class StatistiqueController : Controller
    {
        // GET: Statistique
        public ApplicationDbContext a = new ApplicationDbContext();
        public ServiceStatistic service = new ServiceStatistic(new ApplicationDbContext());
        public ActionResult IndexTop5UserAppreciationParMois()
        {
            ViewBag.liste = service.getTop5UserApprecierParMois();
            return View(service.getTop5UserApprecierParMois());
        }
        public ActionResult IndexTop5UserAppreciationParSemaine()
        {

            ViewBag.liste = service.getTop5UserApprecierParSemaine();
            return View(service.getTop5UserApprecierParSemaine());
        }
        public ActionResult IndexTop5UserObjetParMois()
        {

            ViewBag.liste = service.getTop5UserObjetParMois();
            return View(service.getTop5UserObjetParMois());
        }
        public ActionResult IndexTop5UserObjetParSemaine()
        {

            ViewBag.liste = service.getTop5UserObjetParSemaine();
            return View(service.getTop5UserObjetParSemaine());
        }
        public ActionResult IndexTop5CategoryParMois()
        {
            ViewBag.liste = service.getTop5CategoryParMois();
            return View(service.getTop5CategoryParMois());
        }
        public ActionResult IndexTop5CategoryParSemaine()
        {
            ViewBag.liste = service.getTop5CategoryParSemaine();
            return View(service.getTop5CategoryParSemaine());
        }
    }
}

ProjetAsp/ProjetAsp/Controllers/TradesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjetAsp.Models;

namespace ProjetAsp.Controllers
{
    [Authorize(Roles = "admin, etudiant, professeur, employe")]
    public class TradesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Trades
        public ActionResult Index()
        {
            var tradesSet = db.TradesSet.Include(t => t.Item).Include(t => t.User);
            return View(tradesSet.ToList());
        }

        // GET: Trades/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trade trade = db.TradesSet.Find(id);
            if (trade == null)
            {
                return HttpNotFound();
            }
            return View(trade);
        }

        // GET: Trades/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trade trade = db.TradesSet.Find(id);
            if (trade == null)
            {
                return HttpNotFound();
            }
            ViewBag.ItemID = new SelectList(db.itemsSet, "ItemID", "ItemName", trade.ItemID);
            ViewBag.UserID = new SelectList(db.Users, "Id", "Email", trade.UserID);
            return View(trade);
        }

        // POST: Trades/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TradeID,StartDate,EndDate,UserID,ItemID")] Trade trade)
        {
            if (ModelState.IsValid)
            {
                db.Entry(trade).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ItemID = new SelectList(db.itemsSet, "ItemID", "ItemName", trade.ItemID);
            ViewBag.UserID = new SelectList(db.Users, "Id", "Email", trade.UserID);
            return View(trade);
        }

        // GET: Trades/Delete/5
        public ActionResult Back(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trade trade = db.TradesSet.Find(id);
            if (trade == null)
            {
                return HttpNotFound();
            }
            return View(trade);
        }

        // POST: Trades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Trade trade = db.TradesSet.Find(id);
            db.TradesSet.Remove(trade);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjetAsp/ProjetAsp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Application Maximemes</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(ProjetAsp.Ressources.Views.Item.Emprunter + " Maximemes", "Index", "Items", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink(ProjetAsp.Ressources.Views.Trade.Title, "Index", "Trades")</li>
                    <li>@Html.ActionLink(ProjetAsp.Ressources.Views.Item.Title, "Index", "Items")</li>
                    <li>@Html.ActionLink(ProjetAsp.Ressources.Views.Categorie.Title, "Index", "Categories")</li>
                    <li>@Html.ActionLink(ProjetAsp.Ressources.Views.Categorie.Title, "Index", "Categories")</li>

@if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
{
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@ProjetAsp.Ressources.Views.Statistique.Statistic<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink(ProjetAsp.Ressources.Views.Statistique.TopCatMonth, "IndexTop5CategoryParMois", "Statistique")</li>
                            <li>@Html.ActionLink(ProjetAsp.Ressources.Views.Statistique.TopCatWeek, "IndexTop5CategoryParSemaine", "Statistique")</li>
                            <li>@Html.ActionLink(ProjetAsp.Ressources.Views.Statistique.TopUerObjMonth, "IndexTop5UserObjetParMois", "Statistique")</li>
                            <li>@Html.ActionLink(ProjetAsp.Ressources.Views.Statistique.TopUserObjWeek, "IndexTop5UserObjetParSemaine", "Statistique")</li>  
                            <li>@Html.ActionLink(ProjetAsp.Ressources.Views.Statistique.TopUserApprMonth, "IndexTop5UserAppreciationParMois", "Statistique")</li>
                            <li>@Html.ActionLink(ProjetAsp.Ressources.Views.Statistique.TopUserApprWeek, "IndexTop5UserAppreciationParSemaine", "Statistique")</li>
                        </ul>
                    </li>
}

                </ul>
                @Html.Partial("_LoginPartial")
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@ProjetAsp.Ressources.Views.Home.Language<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("FR", "CultureFR", "Items", new { returnUrl = this.Request.RawUrl }, null)</li>
                            <li>@Html.ActionLink("EN", "CultureEN", "Items", new { returnUrl = this.Request.RawUrl }, null)</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Equipe Maximemes</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>